export const THREE_GAMES_DETAIL_REQUEST = "THREE_GAMES_DETAIL_REQUEST";
export const THREE_GAMES_DETAIL_SUCCESS = "THREE_GAMES_DETAIL_SUCCESS";
export const THREE_GAMES_DETAIL_FAIL = "THREE_GAMES_DETAIL_FAIL";
export const THREE_GAMES_DETAIL_RESET = "THREE_GAMES_DETAIL_RESET";