export const GET_SUMMONER_REQUEST = "GET_SUMMONER_REQUEST";
export const GET_SUMMONER_SUCCESS = "GET_SUMMONER_SUCCESS";
export const GET_SUMMONER_FAIL = "GET_SUMMONER_FAIL";
export const GET_SUMMONER_RESET = "GET_SUMMONER_RESET";